environment:

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"

build: off

install:
  - "%PYTHON%\\python.exe -m pip install regex"

test_script:
  - "%PYTHON%\\python.exe tests\\all_tests.py"
